const SHOP_CATEGORIES = {
    "Electronics": [
        { name: "Wiring & Cables", icon: "🔌" },
        { name: "Switches & Switchgear", icon: "🎚️" },
        { name: "Distribution Panels", icon: "⚡" },
        { name: "Lighting", icon: "💡" },
        { name: "Fan/Cooler/AC", icon: "💨" },
        { name: "TV", icon: "📺" },
        { name: "Freeze", icon: "🧊" },
        { name: "Mobile", icon: "📱" },
        { name: "Installation Material", icon: "🛠️" },
        { name: "Sockets & Plugs", icon: "🔌" },
        { name: "Inverters & Batteries", icon: "🔋" },
        { name: "Pumps & Motors", icon: "🌊" },
        { name: "Tools & Testing", icon: "🧰" },
        { name: "Smart & Security", icon: "🔒" },
        { name: "General", icon: "📦" }
    ],
    "Grocery": [
        { name: "Staples & Grains", icon: "🌾" },
        { name: "Edible Oil & Ghee", icon: "🛢️" },
        { name: "Spices & Masala", icon: "🌶️" },
        { name: "Snacks & Namkeen", icon: "🥨" },
        { name: "Beverages", icon: "🥤" },
        { name: "Dairy & Refrigerator", icon: "🥛" },
        { name: "Bakery Items", icon: "🍞" },
        { name: "Personal Care", icon: "🧴" },
        { name: "Home Cleaning & Household", icon: "🧹" },
        { name: "Baby Care", icon: "👶" },
        { name: "Dry Fruits & Sweets", icon: "🥜" },
        { name: "Instant & Ready to Eat", icon: "🍜" },
        { name: "General", icon: "📦" }
    ],
    "Fashion": [
        { name: "Men's Clothing", icon: "👕", group: "men" },
        { name: "Top Wear", icon: "👕", group: "men" },
        { name: "T-Shirts", icon: "👕", group: "men" },
        { name: "Shirts", icon: "👔", group: "men" },
        { name: "Hoodies & Sweatshirts", icon: "🧥", group: "men" },
        { name: "Bottom Wear", icon: "👖", group: "men" },
        { name: "Jeans (Men)", icon: "👖", group: "men" },
        { name: "Trousers (Men)", icon: "👖", group: "men" },
        { name: "Shorts", icon: "🩳", group: "men" },
        { name: "Track Pants", icon: "👖", group: "men" },
        { name: "Ethnic Wear", icon: "👘", group: "men" },
        { name: "Kurta", icon: "👘", group: "men" },
        { name: "Kurta Pajama", icon: "👘", group: "men" },
        { name: "Sherwani", icon: "🕴️", group: "men" },
        { name: "Casual Wear", icon: "👕", group: "men" },
        { name: "Formal Wear", icon: "👔", group: "men" },
        { name: "Formal Shirts", icon: "👔", group: "men" },
        { name: "Formal Trousers", icon: "👖", group: "men" },
        { name: "Blazers & Suits", icon: "🕴️", group: "men" },
        { name: "Sportswear", icon: "🏃", group: "men" },
        { name: "Gym Wear", icon: "🏃", group: "men" },
        { name: "Track Suits (Men)", icon: "🏃", group: "men" },
        { name: "Winter Wear", icon: "🧥", group: "men" },
        { name: "Jackets (Men)", icon: "🧥", group: "men" },
        { name: "Sweaters (Men)", icon: "🧥", group: "men" },
        { name: "Men's Innerwear", icon: "🩲", group: "men" },
        { name: "Vests", icon: "🎽", group: "men" },
        { name: "Briefs", icon: "🩲", group: "men" },
        { name: "Boxers", icon: "🩳", group: "men" },
        { name: "Men's Nightwear", icon: "🛌", group: "men" },
        { name: "Women's Clothing", icon: "👗", group: "women" },
        { name: "Sarees", icon: "🥻", group: "women" },
        { name: "Kurta Sets", icon: "🥻", group: "women" },
        { name: "Kurtis", icon: "👚", group: "women" },
        { name: "Tops & T-Shirts", icon: "👚", group: "women" },
        { name: "Dresses", icon: "👗", group: "women" },
        { name: "Jeans (Women)", icon: "👖", group: "women" },
        { name: "Trousers (Women)", icon: "👖", group: "women" },
        { name: "Leggings & Palazzos", icon: "👖", group: "women" },
        { name: "Jackets & Coats", icon: "🧥", group: "women" },
        { name: "Blazers", icon: "🧥", group: "women" },
        { name: "Sweatshirts (Women)", icon: "🧥", group: "women" },
        { name: "Sporty Fashion", icon: "🏃‍♀️", group: "women" },
        { name: "Track Suits (Women)", icon: "🏃‍♀️", group: "women" },
        { name: "Gym Wear (Women)", icon: "🏃‍♀️", group: "women" },
        { name: "Winter Wear (Women)", icon: "🧥", group: "women" },
        { name: "Sweaters (Women)", icon: "🧥", group: "women" },
        { name: "Shawls", icon: "🧣", group: "women" },
        { name: "Women's Innerwear", icon: "🩲", group: "women" },
        { name: "Women's Nightwear", icon: "🛌", group: "women" },
        { name: "Dupattas", icon: "🧣", group: "women" },
        { name: "Kids Clothing", icon: "👶", group: "kids" },
        { name: "Kids Tops", icon: "👕", group: "kids" },
        { name: "Kids Bottoms", icon: "👖", group: "kids" },
        { name: "Kids Ethnic Wear", icon: "👘", group: "kids" },
        { name: "Kids Winter Wear", icon: "🧥", group: "kids" },
        { name: "Kids Sweaters", icon: "🧥", group: "kids" },
        { name: "Kids Nightwear", icon: "🛌", group: "kids" },
        { name: "Kids Shoes", icon: "👟", group: "kids" },
        { name: "Thermal Wear", icon: "🧥", group: "none" },
        { name: "Socks", icon: "🧦", group: "none" },
        { name: "Fashion Accessories", icon: "🧦", group: "none" },
        { name: "Belts", icon: "🪢", group: "none" },
        { name: "Caps", icon: "🧢", group: "none" },
        { name: "Scarves", icon: "🧣", group: "none" },
        { name: "Handkerchiefs", icon: "⬜", group: "none" },
        { name: "Gloves", icon: "🧤", group: "none" },
        { name: "General", icon: "📦", group: "none" }
    ],
    "General Store": [
        { name: "Daily Essentials", icon: "🧼" },
        { name: "Snacks & Namkeen", icon: "🥨" },
        { name: "Personal Care", icon: "🧴" },
        { name: "Household Items", icon: "🏠" },
        { name: "Stationery", icon: "✏️" },
        { name: "Cleaning Supplies", icon: "🧹" },
        { name: "Baby Care", icon: "👶" },
        { name: "General", icon: "📦" }
    ],
    "Footwear": [
        { name: "Sports Shoes", icon: "👟", group: "men" },
        { name: "Casual Shoes", icon: "👞", group: "men" },
        { name: "Formal Shoes", icon: "👞", group: "men" },
        { name: "Sneakers", icon: "👟", group: "men" },
        { name: "Sandals", icon: "👡", group: "men" },
        { name: "Slippers / Flip Flops", icon: "🩴", group: "men" },
        { name: "Boots", icon: "🥾", group: "men" },
        { name: "Ethnic Footwear (Mojari / Jutti)", icon: "👘", group: "men" },
        { name: "Heels", icon: "👠", group: "women" },
        { name: "Flats", icon: "🥿", group: "women" },
        { name: "Women Casual Shoes", icon: "👞", group: "women" },
        { name: "Women Sneakers", icon: "👟", group: "women" },
        { name: "Women Sandals", icon: "👡", group: "women" },
        { name: "Women Slippers / Flip Flops", icon: "🩴", group: "women" },
        { name: "Women Boots", icon: "🥾", group: "women" },
        { name: "Women Ethnic Footwear (Jutti / Mojari)", icon: "👘", group: "women" },
        { name: "Kids Sports Shoes", icon: "👟", group: "kids" },
        { name: "Kids Casual Shoes", icon: "👞", group: "kids" },
        { name: "Kids School Shoes", icon: "👟", group: "kids" },
        { name: "Kids Sandals", icon: "👡", group: "kids" },
        { name: "Kids Slippers", icon: "🩴", group: "kids" },
        { name: "Kids Boots", icon: "🥾", group: "kids" },
        { name: "Footwear Accessories", icon: "🧦", group: "none" },
        { name: "General", icon: "📦", group: "none" }
    ],
    "Automobile": [
        { name: "Parts & Accessories", icon: "🔧" },
        { name: "Oils & Lubricants", icon: "🛢️" },
        { name: "Batteries", icon: "🔋" },
        { name: "Tires & Wheels", icon: "⚙️" },
        { name: "Car Care & Cleaning", icon: "✨" },
        { name: "Tools & Equipment", icon: "🧰" },
        { name: "General", icon: "📦" }
    ],
    "Bakery": [
        { name: "Breads", icon: "🍞" },
        { name: "Cakes & Pastries", icon: "🎂" },
        { name: "Cookies & Biscuits", icon: "🍪" },
        { name: "Sweets & Desserts", icon: "🍰" },
        { name: "Savory Items", icon: "🥐" },
        { name: "Custom Orders", icon: "📝" },
        { name: "General", icon: "📦" }
    ],
    "Dhaba": [
        { name: "Veg Dishes", icon: "🥗" },
        { name: "Non-Veg Dishes", icon: "🍗" },
        { name: "Rice & Roti", icon: "🍚" },
        { name: "Snacks & Starters", icon: "🍟" },
        { name: "Beverages", icon: "🥤" },
        { name: "Combo Meals", icon: "🍱" },
        { name: "General", icon: "📦" }
    ],
    "Furniture": [
        { name: "Beds & Mattresses", icon: "🛏️" },
        { name: "Sofas & Chairs", icon: "🛋️" },
        { name: "Tables & Desks", icon: "🪑" },
        { name: "Storage & Cabinets", icon: "🗄️" },
        { name: "Home Decor", icon: "🖼️" },
        { name: "Office Furniture", icon: "💼" },
        { name: "General", icon: "📦" }
    ],
    "Hardware": [
        { name: "Tools & Equipment", icon: "🔨" },
        { name: "Building Materials", icon: "🧱" },
        { name: "Paint & Supplies", icon: "🎨" },
        { name: "Plumbing", icon: "🚰" },
        { name: "Electrical Items", icon: "💡" },
        { name: "Locks & Security", icon: "🔒" },
        { name: "General", icon: "📦" }
    ],
    "Jewelers": [
        { name: "Gold Jewelry", icon: "💛" },
        { name: "Silver Jewelry", icon: "🤍" },
        { name: "Diamond Jewelry", icon: "💎" },
        { name: "Imitation / Fashion", icon: "✨" },
        { name: "Bridal Jewelry", icon: "👰" },
        { name: "Repairs & Custom", icon: "🔧" },
        { name: "General", icon: "📦" }
    ],
    "Medical": [
        { name: "Medicines", icon: "💊" },
        { name: "Health Supplements", icon: "💪" },
        { name: "Medical Devices", icon: "🩺" },
        { name: "First Aid", icon: "🩹" },
        { name: "Baby Care", icon: "👶" },
        { name: "Personal Care", icon: "🧴" },
        { name: "General", icon: "📦" }
    ],
    "Mobile Shop": [
        { name: "Smartphones", icon: "📱" },
        { name: "Feature Phones", icon: "📞" },
        { name: "Accessories", icon: "🎧" },
        { name: "Chargers & Cables", icon: "🔌" },
        { name: "Cases & Covers", icon: "📲" },
        { name: "Repairs & Services", icon: "🔧" },
        { name: "General", icon: "📦" }
    ],
    "Non-Veg": [
        { name: "Chicken", icon: "🍗" },
        { name: "Mutton", icon: "🍖" },
        { name: "Fish", icon: "🐟" },
        { name: "Eggs", icon: "🥚" },
        { name: "Seafood", icon: "🦐" },
        { name: "Frozen Items", icon: "❄️" },
        { name: "General", icon: "📦" }
    ],
    "Printing & Digital": [
        { name: "Printing Services", icon: "🖨️" },
        { name: "Photocopying", icon: "📄" },
        { name: "Scanning", icon: "📷" },
        { name: "Lamination", icon: "🧾" },
        { name: "Binding", icon: "📚" },
        { name: "Design Services", icon: "🎨" },
        { name: "General", icon: "📦" }
    ],
    "Restaurant": [
        { name: "Veg Dishes", icon: "🥗" },
        { name: "Non-Veg Dishes", icon: "🍗" },
        { name: "Chinese", icon: "🥡" },
        { name: "South Indian", icon: "🥘" },
        { name: "Beverages", icon: "🥤" },
        { name: "Desserts", icon: "🍨" },
        { name: "General", icon: "📦" }
    ],
    "Salon": [
        { name: "Haircut & Styling", icon: "✂️" },
        { name: "Hair Color", icon: "🎨" },
        { name: "Facial & Cleanup", icon: "💆" },
        { name: "Spa & Massage", icon: "💅" },
        { name: "Bridal Services", icon: "👰" },
        { name: "Men's Grooming", icon: "🧔" },
        { name: "General", icon: "📦" }
    ],
    "Seeds & Fertilizers": [
        { name: "Seeds", icon: "🌱" },
        { name: "Chemical Fertilizers", icon: "🧪" },
        { name: "Organic Fertilizers", icon: "♻️" },
        { name: "Pesticides", icon: "🦟" },
        { name: "Farming Tools", icon: "🚜" },
        { name: "Plant Care", icon: "🌿" },
        { name: "General", icon: "📦" }
    ],
    "Sports": [
        { name: "Cricket", icon: "🏏" },
        { name: "Football", icon: "⚽" },
        { name: "Badminton", icon: "🏸" },
        { name: "Gym Equipment", icon: "🏋️" },
        { name: "Sportswear", icon: "🎽" },
        { name: "Indoor Games", icon: "♟️" },
        { name: "Trophies & Medals", icon: "🏆" },
        { name: "General", icon: "📦" }
    ],
    "Stationery": [
        { name: "Writing Supplies", icon: "✏️" },
        { name: "Notebooks & Diaries", icon: "📓" },
        { name: "Art & Craft", icon: "🎨" },
        { name: "Office Supplies", icon: "📎" },
        { name: "School Items", icon: "🎒" },
        { name: "Printing Paper", icon: "📄" },
        { name: "General", icon: "📦" }
    ],
    "Vegetables & Fruits": [
        { name: "Fresh Vegetables", icon: "🥦" },
        { name: "Fresh Fruits", icon: "🍎" },
        { name: "Seasonal Items", icon: "🌽" },
        { name: "Exotic", icon: "🥝" },
        { name: "Organic", icon: "🌿" },
        { name: "Herbs", icon: "🌿" },
        { name: "General", icon: "📦" }
    ],
    "Beauty/Cosmetics": [
        { name: "Makeup", icon: "💄" },
        { name: "Skincare", icon: "🧴" },
        { name: "Haircare", icon: "💇‍♀️" },
        { name: "Fragrance", icon: "🌺" },
        { name: "Personal Care", icon: "🛁" },
        { name: "Tools & Accessories", icon: "💅" },
        { name: "General", icon: "📦" }
    ],
    "Coaching": [
        { name: "Tuition (School)", icon: "📚" },
        { name: "Competitive Exams", icon: "📝" },
        { name: "Language Classes", icon: "🗣️" },
        { name: "Arts & Hobbies", icon: "🎨" },
        { name: "Sports Coaching", icon: "⚽" },
        { name: "Professional Skills", icon: "💻" },
        { name: "General", icon: "📦" }
    ],
    "Sweet Shop": [
        { name: "Traditional Sweets", icon: "🍮" },
        { name: "Mithai", icon: "🧆" },
        { name: "Dry Fruit Sweets", icon: "🥜" },
        { name: "Chocolates", icon: "🍫" },
        { name: "Ice Cream & Kulfi", icon: "🍦" },
        { name: "Namkeen & Savories", icon: "🥨" },
        { name: "Seasonal Specials", icon: "🌸" },
        { name: "Gift Boxes", icon: "🎁" },
        { name: "General", icon: "📦" }
    ]
};

export { SHOP_CATEGORIES };
